merge

diff --git a/exec/check/gtest/run b/exec/check/gtest/run
--- a/exec/check/gtest/run
+++ b/exec/check/gtest/run
@@ -1,27 +1,18 @@
 #!/bin/bash
 #
-# 内存测试脚本
+# Google Test 测试脚本
 #
-# 用法：$0 <datadir> <timelimit> <chrootdir> <workdir> <run-uuid> <run>
+# 用法：$0 <datadir> <timelimit> <chrootdir> <workdir> <run-uuid>
 #
-# <datadir>      包含数据文件的文件夹的绝对路径
-# <timelimit>    运行时间限制，格式为 %d:%d，如 1:3 表示测试点时间限制
-#                为 1s，如果运行时间超过 3s 则结束程序
+# <datadir>      此程序不使用数据
+# <timelimit>    此程序受 SCRIPTTIMELIMIT 时限限制
 # <chrootdir>    子环境
 # <workdir>      程序的工作文件夹，为了保证安全，请务必将运行路径设置
 #                为空文件夹，特别是保证不可以包含标准输出文件
 # <run-uuid>     运行的 uuid，用于索引运行文件夹位置
-# <run>          运行程序的脚本的绝对路径
 #
 # 必须包含的环境变量：
-#   RUNGUARD        runguard 的路径
-#   RUNUSER         选手程序运行的账户
-#   RUNGROUP        选手程序运行的账户组
-#
-# 可选环境变量
-#   MEMLIMIT     运行内存限制，单位为 KB
-#   PROCLIMIT    进程数限制
-#   FILELIMIT    文件写入限制，单位为 KB
+# "RUNGUARD"     runguard 的路径
 #
 # 默认的比较脚本都可以放在配置服务中
 
@@ -74,21 +65,6 @@ if [ -n "$CPUSET" ]; then
     CPUSET_OPT="-P $CPUSET"
 fi
 
-MEMLIMIT_OPT=""
-if [ -n "$MEMLIMIT" ]; then
-    MEMLIMIT_OPT="--memory-limit $MEMLIMIT"
-fi
-
-FILELIMIT_OPT=""
-if [ -n "$FILELIMIT" ]; then
-    FILELIMIT_OPT="--file-limit $FILELIMIT --stream-size $FILELIMIT"
-fi
-
-PROCLIMIT_OPT=""
-if [ -n "$PROCLIMIT" ]; then
-    PROCLIMIT_OPT="--nproc $PROCLIMIT"
-fi
-
 LOGFILE="$LOGDIR/judge.$(hostname | cut -d . -f 1).log"
 LOGLEVEL=$LOG_DEBUG
 PROGNAME="$(basename "$0")"
@@ -102,10 +78,11 @@ fi
 GAINROOT="sudo -n"
 PROGRAM="compile/run"
 
-[ $# -ge 6 ] || error "not enough arguments"
+[ $# -ge 4] || error "not enough arguments"
 
 DATADIR="$1"; shift
 TIMELIMIT="$1"; shift
+MEMLIMIT="$1"; shift
 CHROOTDIR="$1"; shift
 WORKDIR="$1"; shift
 RUN_UUID="$1"; shift
@@ -144,34 +121,36 @@ mkdir -m 0777 -p "$RUNDIR/run" # 运行的临时文件都在这里
 mkdir -m 0777 -p "$RUNDIR/feedback"
 mkdir -m 0777 -p "$RUNDIR/work"
 mkdir -m 0777 -p "$RUNDIR/work/judge"
-mkdir -m 0777 -p "$RUNDIR/work/run"
 mkdir -m 0777 -p "$RUNDIR/merged"
 # 将测试数据文件夹（内含输入数据，且其中 testdata.in 为标准输入数据文件名），编译好的程序，运行文件夹通过 overlayfs 绑定
 $GAINROOT mount -t aufs none -odirs="$RUNDIR/run"=rw:"$WORKDIR/compile"=ro:"$TESTIN"=ro "$RUNDIR/work/judge"
-$GAINROOT mount --bind -o ro "$RUN_SCRIPT" "$RUNDIR/work/run"
 $GAINROOT mount -t aufs none -odirs="$RUNDIR/work"=rw:"$CHROOTDIR"=ro "$RUNDIR/merged"
 
 chroot_start "$CHROOTDIR" "$RUNDIR/merged"
 
 # 我们不检查选手程序的返回值，比如 C 程序的 main 函数没有写 return 会导致返回值非零，这种不是崩溃导致的
-runcheck $GAINROOT "$RUNGUARD" ${DEBUG:+-v} $CPUSET_OPT $MEMLIMIT_OPT $FILELIMIT_OPT $PROCLIMIT_OPT \
+runcheck $GAINROOT "$RUNGUARD" ${DEBUG:+-v} $CPUSET_OPT \
     --root "$RUNDIR/merged" \
     --work /judge \
+    --nproc $PROCLIMIT \
     --no-core-dumps \
+    --streamsize $FILELIMIT \
     --user "$RUNUSER" \
     --group "$RUNGROUP" \
-    --wall-time "$TIMELIMIT" \
+    --wall-time $TIMELIMIT \
+    --memory-limit $MEMLIMIT \
+    --file-limit $FILELIMIT \
     --standard-output-file valgrind.xml \
     --standard-error-file program.err \
     --out-meta program.meta -- \
-    valgrind --leak-check=full --undef-value-errors=yes --track-origins=yes --xml=yes --xml-fd=1 -- \
-    /run/run testdata.in program.out /judge/run 2>runguard.err
+    /judge/run  2>runguard.err
 
 chroot_stop "$CHROOTDIR" "$RUNDIR/merged"
 
-force_umount "$RUNDIR/work/judge"
-force_umount "$RUNDIR/work/run"
-force_umount "$RUNDIR/merged"
+force_umount "$RUNDIR/work/judge" >/dev/null 2>&1  || /bin/true
+force_umount "$RUNDIR/work/judge_utils" >/dev/null 2>&1  || /bin/true
+force_umount "$RUNDIR/work/run" >/dev/null 2>&1  || /bin/true
+force_umount "$RUNDIR/merged" >/dev/null 2>&1  || /bin/true
 rm -rf "$RUNDIR/run"
 rm -rf "$RUNDIR/merged"
 rm -rf "$RUNDIR/work"
@@ -213,7 +192,7 @@ if grep -E '^output-truncated: ([a-z]+,)*stdout(,[a-z]+)*' program.meta >/dev/nu
     cleanexit ${E_OUTPUT_LIMIT:-1}
 fi
 
-runcheck python3 "$PROGNAME/convert.py" valgrind.xml "$RUNDIR/feedback/report.txt" 2>feedback/judgemessage.txt
+runcheck python3 "$PROGNAME/convert.py" gtest.xml $RUNDIR/feedback/report.txt 2>feedback/judgemessage.txt
 case $exitcode in
     0)
         echo "Accepted" >> system.out
@@ -226,7 +205,7 @@ case $exitcode in
         cleanexit ${E_WRONG_ANSWER:-1}
         ;;
     *)
-        echo "Comparing failed with exitcode $exitcode" >> system.out
+        logmsg $LOG_ERR "Comparing failed with exitcode $exitcode, compare script output:\\n$(cat feedback/judgemessage.txt)"
         cleanexit ${E_COMPARE_ERROR:-1}
         ;;
 esac
diff --git a/exec/check/standard/run b/exec/check/standard/run
--- a/exec/check/standard/run
+++ b/exec/check/standard/run
@@ -106,16 +106,15 @@ fi
 GAINROOT="sudo -n"
 PROGRAM="compile/run"
 
-[ $# -ge 4 ] || error "not enough arguments"
+[ $# -ge 7 ] || error "not enough arguments"
 
 DATADIR="$1"; shift
 TIMELIMIT="$1"; shift
 CHROOTDIR="$1"; shift
 WORKDIR="$1"; shift
 RUN_UUID="$1"; shift
-RUN_SCRIPT="$1"
-COMPARE_SCRIPT="$2"
-COMPARE_ARGS="$3"
+RUN_SCRIPT="$1"; shift
+COMPARE_SCRIPT="$1"
 
 TESTIN="$DATADIR/input"
 TESTOUT="$DATADIR/output"
@@ -179,12 +178,11 @@ runcheck $GAINROOT "$RUNGUARD" ${DEBUG:+-v} $CPUSET_OPT $MEMLIMIT_OPT $FILELIMIT
     /run/run testdata.in program.out /judge/run 2>runguard.err
 
 # 比较选手程序输出
-logmsg $LOG_INFO "Comparing output"
+echo "Comparing output" >> system.out
 force_umount "$RUNDIR/merged/judge"
 $GAINROOT mount --bind "$RUNDIR/feedback" "$RUNDIR/merged/feedback"
 $GAINROOT mount -t aufs none -odirs="$RUNDIR/run"=rw:"$WORKDIR/compile"=ro:"$TESTIN"=ro:"$TESTOUT"=ro "$RUNDIR/merged/judge"
 
-exitcode=0
 runcheck $GAINROOT "$RUNGUARD" ${DEBUG:+-v} $CPUSET_OPT \
     --root "$RUNDIR/merged" \
     --work /judge \
@@ -194,9 +192,11 @@ runcheck $GAINROOT "$RUNGUARD" ${DEBUG:+-v} $CPUSET_OPT \
     --memory-limit $SCRIPTMEMLIMIT \
     --wall-time $SCRIPTTIMELIMIT \
     --file-limit $SCRIPTFILELIMIT \
+    --standard-output-file compare.out \
+    --standard-error-file compare.err \
     --out-meta compare.meta \
     -VJUDGE_UTILS=/judge_utils -- \
-    "/compare/run" testdata.in program.out testdata.out /feedback > compare.tmp 2>&1
+    "/compare/run" testdata.in program.out testdata.out /feedback 2>>runguard.err
 
 chroot_stop "$CHROOTDIR" "$RUNDIR/merged"
 
@@ -209,25 +209,29 @@ force_umount "$RUNDIR/merged/feedback"
 force_umount "$RUNDIR/merged"
 rm -rf "$RUNDIR/merged"
 rm -rf "$RUNDIR/work"
-# RUNDIR 还剩下 compare.meta, compare.out, program.meta, program.err, system.out, runguard.err 供评测客户端检查
+# RUNDIR 还剩下 compare.meta, compare.out, compare.err program.meta, program.err, system.out, runguard.err 供评测客户端检查
 # RUNDIR 由评测客户端删除
 
-# Append output validator error messages
-# TODO: display extra
-if [ -s feedback/judgeerror.txt ]; then
-	printf "\\n---------- output validator (error) messages ----------\\n" >> feedback/judgemessage.txt
-	cat feedback/judgeerror.txt >> feedback/judgemessage.txt
+# Make sure that all feedback files are owned by the current
+# user/group, so that we can append content.
+$GAINROOT chown -R "$(id -un):" "$RUNDIR/feedback"
+chmod -R go-w feedback
+
+# 记录比较器的标准输出
+if [ -s compare.out ]; then
+	printf "\\n---------- output validator stdout messages ----------\\n" >> system.out
+	cat compare.out >> system.out
 fi
 
-# Append output validator stdin/stderr - display extra?
-if [ -s compare.tmp ]; then
-	printf "\\n---------- output validator stdout/stderr messages ----------\\n" >> feedback/judgemessage.txt
-	cat compare.tmp >> feedback/judgemessage.txt
+# 记录比较器的标准错误流
+if [ -s compare.err ]; then
+	printf "\\n---------- output validator stderr messages ----------\\n" >> system.out
+	cat compare.err >> system.out
 fi
 
-logmsg $LOG_DEBUG "checking compare script exit-status: $exitcode"
+echo "checking compare script exit-status: $exitcode" >> system.out
 if grep '^time-result: .*timelimit' compare.meta >/dev/null 2>&1; then
-    logmsg $LOG_ERR "Comparing aborted after $SCRIPTTIMELIMIT seconds, compare script output: \\n$(cat compare.tmp)"
+    echo "Comparing aborted after $SCRIPTTIMELIMIT seconds" >> system.out
     cleanexit ${E_COMPARE_ERROR:-1}
 fi
 
@@ -235,7 +239,7 @@ if [ ! -r program.meta ]; then
     error "'program.meta' is not readable"
 fi
 
-logmsg $LOG_DEBUG "Checking program run status"
+echo "Checking program run status" >> system.out
 
 timeused=$(grep '^time-used: '    program.meta | sed 's/time-used: //'   )
 cputime=$( grep '^cpu-time: '     program.meta | sed 's/cpu-time: //'    )
@@ -291,7 +295,7 @@ if [ "$progexit" -ne 0 ]; then
 fi
 
 if [ $exitcode -eq $RESULT_PC ] && [ ! -f "$RUNDIR/feedback/score.txt" ]; then
-    logmsg $LOG_ERR "Compare script reports partial correct without score record."
+    echo "Compare script reports partial correct without score record." >> system.out
     cleanexit ${E_COMPARE_ERROR:-1}
 fi
 
@@ -317,7 +321,7 @@ case $exitcode in
         cleanexit ${E_PARTIAL_CORRECT:-1}
         ;;
     *)
-        logmsg $LOG_ERR "Comparing failed with exitcode $exitcode, compare script output:\\n$(cat feedback/judgemessage.txt)"
+        echo "Comparing failed with exitcode $exitcode" >> system.out
         cleanexit ${E_COMPARE_ERROR:-1}
         ;;
 esac
